### ISSUE TITLE
application library

### ISSUE THREAD

**Issue by ThreaT** [servalproject/batphone#108]
Would it be possible to abstract the mesh networking facilities into a maven dependency that can be used as a standalone library on Java applications, to provide applications with a custom mesh implementation?

**Comment by lakeman** [comment]
That depends on what you mean.
Our routing protocol and services are implemented in a native library, with a plain Java API in https://github.com/servalproject/serval-dna/.
Our experimental methods for adhoc support is all in this repository.
We have also considered building a client library for other applications to access our networking and file replication services, so that only one instance of the core runtime is required. Perhaps splitting some of our features into separate apps.

But are we going to build a maven dependency? Not in the near future.
